### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TaylanTatli** [janbina/swm#13]
Can't start it with xinitrc. So i tried to run it in Xephyr so i can see what's wrong. Here is the output:

```
XGB: conn.go:47: Could not get authority info: EOF
XGB: conn.go:48: Trying connection without authority info...
2020/06/11 21:30:01 Setting selection owner.
2020/06/11 21:30:01 Getting selection owner.
2020/06/11 21:30:01 Swm is now your wm.
2020/06/11 21:30:01 Trying to execute config
2020/06/11 21:30:01 Executing config file "/home/taylantatli/.config/swm/swmrc"
2020/06/11 21:30:01 Error executing config file: exit status 1
2020/06/11 21:30:01 Handle root client message: _NET_NUMBER_OF_DESKTOPS (ClientMessage {Sequence: 171, Format: 32, Window: 921, Type: 241})
2020/06/11 21:30:05 Map request: MapRequest {Sequence: 182, Parent: 921, Window: 6291469}
2020/06/11 21:30:05 Client message _NET_ACTIVE_WINDOW: ClientMessage {Sequence: 274, Format: 32, Window: 6291469, Type: 254}
2020/06/11 21:30:06 Destroy notify: DestroyNotify {Sequence: 290, Event: 6291469, Window: 6291469}
[xgbutil] xwindow.go:326: BadWindow {NiceName: Window, Sequence: 315, BadValue: 6291469, MinorOpcode: 0, MajorOpcode: 4}
[xgbutil] xgbutil.go:240: BadWindow {NiceName: Window, Sequence: 306, BadValue: 6291469, MinorOpcode: 0, MajorOpcode: 7}
[xgbutil] xgbutil.go:240: BadWindow {NiceName: Window, Sequence: 319, BadValue: 6291469, MinorOpcode: 0, MajorOpcode: 6}
2020/06/11 21:30:08 Map request: MapRequest {Sequence: 324, Parent: 921, Window: 6291469}
2020/06/11 21:30:08 Client message _NET_ACTIVE_WINDOW: ClientMessage {Sequence: 397, Format: 32, Window: 6291469, Type: 254}
2020/06/11 21:30:10 Client message _NET_WM_STATE: ClientMessage {Sequence: 423, Format: 32, Window: 6291469, Type: 276}
2020/06/11 21:30:10 Wm state client message: 2, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ
2020/06/11 21:30:10 Client message _NET_WM_STATE: ClientMessage {Sequence: 455, Format: 32, Window: 6291469, Type: 276}
2020/06/11 21:30:10 Wm state client message: 2, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ
2020/06/11 21:30:12 Destroy notify: DestroyNotify {Sequence: 483, Event: 6291469, Window: 6291469}
[xgbutil] xwindow.go:326: BadWindow {NiceName: Window, Sequence: 510, BadValue: 6291469, MinorOpcode: 0, MajorOpcode: 4}
[xgbutil] xgbutil.go:240: BadWindow {NiceName: Window, Sequence: 501, BadValue: 6291469, MinorO
pcode: 0, MajorOpcode: 7}
[xgbutil] xgbutil.go:240: BadWindow {NiceName: Window, Sequence: 514, BadValue: 6291469, MinorOpcode: 0, MajorOpcode: 6}
2020/06/11 21:30:14 Map request: MapRequest {Sequence: 519, Parent: 921, Window: 6291469}
2020/06/11 21:30:14 Client message _NET_ACTIVE_WINDOW: ClientMessage {Sequence: 614, Format: 32, Window: 6291469, Type: 254}
2020/06/11 21:30:18 Destroy notify: DestroyNotify {Sequence: 618, Event: 6291469, Window: 6291469}
[xgbutil] xwindow.go:326: BadWindow {NiceName: Window, Sequence: 643, BadValue: 6291469, MinorOpcode: 0, MajorOpcode: 4}
[xgbutil] xgbutil.go:240: BadWindow {NiceName: Window, Sequence: 634, BadValue: 6291469, MinorOpcode: 0, MajorOpcode: 7}
[xgbutil] xgbutil.go:240: BadWindow {NiceName: Window, Sequence: 647, BadValue: 6291469, MinorOpcode: 0, MajorOpcode: 6}
XGB: xgb.go:403: A read error is unrecoverable: EOF
XGB: xgb.go:403: A read error is unrecoverable: EOF
panic: close of closed channel

goroutine 22 [running]:
github.com/BurntSushi/xgb.(*Conn).Close(...)
	/home/taylantatli/.go/pkg/mod/github.com/!burnt!sushi/xgb@v0.0.0-20160522181843-27f122750802/xgb.go:140
github.com/BurntSushi/xgb.(*Conn).readResponses(0xc0001382c0)
	/home/taylantatli/.go/pkg/mod/github.com/!burnt!sushi/xgb@v0.0.0-20160522181843-27f122750802/xgb.go:405 +0x25a
created by github.com/BurntSushi/xgb.postNewConn
	/home/taylantatli/.go/pkg/mod/github.com/!burnt!sushi/xgb@v0.0.0-20160522181843-27f122750802/xgb.go:133 +0x206
```

xdotool and wmctrl commands are working. but not swmctl commands.

**Comment by janbina** [comment]
Hey, thanks for the report.
You say that starting with xinitrc does not work, which would imply some problems in initialization or swmrc, but then the crash happens 18 seconds after startup, so that's not probably the case...
Does the crash happen just randomly, or is it a reaction to some action (smwctl command, window creation, ...)? If so, which?

**Comment by TaylanTatli** [comment]
if you mean lines starting with `XGB: xgb.go:403: A read error is unrecoverable: EOF`, it's because i closed Xephyr. 

if i launch swm and do nothing all i get is these:
```
XGB: conn.go:47: Could not get authority info: EOF
XGB: conn.go:48: Trying connection without authority info...
2020/06/11 22:02:56 Setting selection owner.
2020/06/11 22:02:56 Getting selection owner.
2020/06/11 22:02:56 Swm is now your wm.
2020/06/11 22:02:56 Trying to execute config
2020/06/11 22:02:56 Executing config file "/home/taylantatli/.config/swm/swmrc"
2020/06/11 22:02:56 Error executing config file: exit status 1
2020/06/11 22:02:56 Handle root client message: _NET_NUMBER_OF_DESKTOPS (ClientMessage {Sequence: 171, Format: 32, Window: 921, Type: 241})
```

**Comment by janbina** [comment]
Ok, so the only problem is the `Error executing config file...` then?
Can you share the `swmrc` file, or find out what's causing the problem in there? It might be some swmctl command since you said that they do not work - what happens if you run those commands from cli? There should be some output.

**Comment by TaylanTatli** [comment]
my swmcr:
```
#!/bin/bash

sxhkd -c ~/.config/swm/sxhkdrc &

xdotool set_num_desktops 5

swmctl config border 1 B0BEC5 00BCD4 F44336
swmctl config border-top 3 B0BEC5 00BCD4 F44336

swmctl config font "/.local/share/fonts/Roboto/RobotoCondensed-Bold.ttf"
swmctl config info-bg-color 00BCD4
swmctl config info-text-color FFFFFF

swmctl config move-drag-shortcut Mod1-1
swmctl config resize-drag-shortcut Mod1-3

swmctl group mode auto # or sticky

swmctl group names 1 2 3 4 5
```

my sxhkdrc:
```
# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# application launcher
super + r
  rofi -show drun

super + shift + r
  rofi -show run

# terminal emulator
super + Return
  kitty

# function keys
XF86AudioRaiseVolume
  volctl +

XF86AudioLowerVolume
  volctl -

XF86AudioMute
  volctl toggle

XF86MonBrightnessUp
  brightness +

XF86MonBrightnessDown
  brigtness -

Print
  screenshot -f

super + Print
  screenshot -a

super + shift + Print
  screenshot -o

super + shift + alt + Print
  screenshot -e

# Apps
super + e
  emoji-picker | xclip -selection clipboard

super + c
  xcolor -f HEX | tr -d '\n' | xclip -selection clipboard

### SWM KEYS ###

# close active window
super + shift + w
    xdotool getactivewindow windowclose

# toggle active window maximized state
super + m
    wmctrl -r :ACTIVE: -b toggle,maximized_vert,maximized_horz

# minimize active window
super + n
    wmctrl -r :ACTIVE: -b add,hidden

# cycle windows
alt + Tab
    swmctl cycle-win
@Alt_L
    swmctl cycle-win-end

# tile active window left/right
super + alt + {Left,Right}
    swmctl moveresize -o {w,e} -wr .5 -hr 1

# move active window by 20 px west/south/north/east
super + {Left, Down, Up, Right}
    swmctl move -{w,s,n,e} 20

# enlarge active window by 20px west/south/north/east
super + shift + {Left, Down, Up, Right}
    swmctl resize -{w,s,n,e} 20

# move active window to group 0-9
super + shift + {1-9,0}
    swmctl group set -g {0-9}
    # also xdotool getactivewindow set_desktop_for_window {0-9}

# toggle visibility of group 0-9
super + ctrl + {1-9,0}
    swmctl group toggle {0-9}

# show only group 0-9
super + {1-9,0}
    swmctl group only {0-9}
    # also xdotool set_desktop {0-9}
```
when i execute swmctl -replace:
```
XGB: conn.go:47: Could not get authority info: EOF
XGB: conn.go:48: Trying connection without authority info...
2020/06/12 20:32:21 Setting selection owner.
2020/06/12 20:32:21 Getting selection owner.
2020/06/12 20:32:21 Swm is now your wm.
2020/06/12 20:32:21 Trying to execute config
2020/06/12 20:32:21 Executing config file "/home/taylantatli/.config/swm/swmrc"
2020/06/12 20:32:21 Error executing config file: exit status 1
2020/06/12 20:32:21 Handle root client message: _NET_NUMBER_OF_DESKTOPS (ClientMessage {Sequence: 171, Format: 32, Window: 921, Type: 241})
```

xprop when swm is the wm:
```
_NET_ACTIVE_WINDOW(WINDOW): window id # 0xe0000d
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x60000d, 0xa0000d, 0xe0000d
_NET_CLIENT_LIST(WINDOW): window id # 0x60000d, 0xa0000d, 0xe0000d
_NET_DESKTOP_NAMES(UTF8_STRING) = "G.1", "G.2", "G.3", "G.4", "G.5"
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0xc00002
_NET_SUPPORTED(ATOM) = _NET_SUPPORTED, _NET_CLIENT_LIST, _NET_NUMBER_OF_DESKTOPS, _NET_DESKTOP_GEOMETRY, _NET_CURRENT_DESKTOP, _NET_DESKTOP_NAMES, _NET_ACTIVE_WINDOW, _NET_SUPPORTING_WM_CHECK, _NET_CLOSE_WINDOW, _NET_MOVERESIZE_WINDOW, _NET_RESTACK_WINDOW, _NET_WM_NAME, _NET_WM_DESKTOP, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU, _NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_COMBO, _NET_WM_WINDOW_TYPE_DND, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_STATE, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_ABOVE, _NET_WM_STATE_BELOW, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_STATE_FOCUSED, _NET_WM_ALLOWED_ACTIONS, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_AM_ACTION_BELOW, _NET_WM_STRUT_PARTIAL, _NET_WM_ICON, _NET_FRAME_EXTENTS, WM_TRANSIENT_FOR
_NET_WORKAREA(CARDINAL) = 0, 0, 1366, 768, 0, 0, 1366, 768, 0, 0, 1366, 768, 0, 0, 1366, 768, 0, 0, 1366, 768
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0
_NET_DESKTOP_GEOMETRY(CARDINAL) = 1366, 768
WM_CLASS(STRING) = 
_SWM_VISIBLE_GROUPS(CARDINAL) = 
_NET_CURRENT_DESKTOP(CARDINAL) = 4294967295
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 0
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""
```

when running swmctl command:
```
XGB: conn.go:47: Could not get authority info: EOF
XGB: conn.go:48: Trying connection without authority info...
2020/06/12 20:30:50 Cannot initialize window manager: another window manager is already running
```

**Comment by janbina** [comment]
Alright, thanks for the info. Some observations:
- from `_NET_DESKTOP_NAMES(UTF8_STRING) = "G.1"...`, it seems that swm is running, those are names used by default. It also seems that your `set_num_desktops 5` works, as there are five of them, but `swmctl group names 1 2 3 4 5` does not.
- there is probably a problem in the font path in your swmrc: `/.local/share/...`, you probably forgot `~`, but I don't think that's why it fails.
- the swmctl output is weird. It does not try to initialize window manager obviously, this error comes from swm itself - are you sure you are running swmctl?

What to try:
- run `swmctl` command when swm is not running. It just writes provided command to the socket, so it will do nothing bad. The output should be something like `Cannot connect to swm. Is swm running on display X?`
- fix the font path in swmrc. If it does not help, try it with some very minimal swmrc file, something like:
```
xdotool set_num_desktops 5
swmctl group names 1 2 3 4 5
```
- make sure that swmrc file is executable. You can also try to run it from the command line when swm is running, it should give you more output this way. Just make sure your DISPLAY environment variable is set to Xephyrs display id - this also applies for swmctl commands.

**Comment by TaylanTatli** [comment]
>     * the swmctl output is weird. It does not try to initialize window manager obviously, this error comes from swm itself - are you sure you are running swmctl?

I'm so sorry, it seems I install `swm` as `swmctl`. :disappointed:
It's working now, sorry again.

**Comment by TaylanTatli** [comment]
since i can use swm now, i have some problems. do yo want me to open a new issue?

**Comment by janbina** [comment]
Ok, good to know. Yes, feel free to open new issue.
